name: settings
description: "Módulo de configuración y backup para MyLifeOS."
publish_to: 'none'
version: 0.0.1

resolution: workspace

environment:
  sdk: ^3.3.4

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^3.2.1
  file_picker: ^8.3.4
  shared_preferences: ^2.5.4
  core:
    path: ../../core

  flutter_secure_storage: any
  data: any
  domain: any
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
